# Generated by Django 4.1.6 on 2023-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
