# Generated by Django 4.1.6 on 2023-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животое', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(max_length=64, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.CharField(max_length=32, verbose_name='Вид'),
        ),
    ]
