# Generated by Django 4.1.6 on 2023-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_options_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='media/photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
