# Generated by Django 4.1.6 on 2023-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default=2, max_length=30, verbose_name='имя'),
            preserve_default=False,
        ),
    ]
